<template>
  <div class="home">
    <h1>Home</h1>
    <PostList v-if="showPosts" v-bind:posts="posts" />
    <button @click="showPosts = !showPosts">toggle posts</button>
    <button @click="posts.pop()">delete a posts</button> <!-- .pop() will remove a post -->
  </div>
</template>

<script>
import PostList from '../components/PostList.vue'
import { ref } from 'vue'

export default {
  name: 'HomeView',
  components: { PostList },
  setup() {
    const posts = ref([
      { title: 'welcome to the blog', body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vulputate odio ut enim blandit volutpat maecenas volutpat blandit. Bibendum enim facilisis gravida neque convallis a cras semper. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Arcu odio ut sem nulla pharetra diam sit amet. Nisl vel pretium lectus quam id. Nisl condimentum id venenatis a. Faucibus in ornare quam viverra orci. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Turpis tincidunt id aliquet risus. Ullamcorper velit sed ullamcorper morbi tincidunt. Sit amet risus nullam eget felis eget nunc. Velit scelerisque in dictum non consectetur a. Vel risus commodo viverra maecenas. Viverra maecenas accumsan lacus vel. Quis ipsum suspendisse ultrices gravida. Nulla facilisi morbi tempus iaculis urna id volutpat. Convallis tellus id interdum velit laoreet id. Molestie nunc non blandit massa. Phasellus egestas tellus rutrum tellus. Sagittis eu volutpat odio facilisis mauris sit. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Lorem ipsum dolor sit amet consectetur adipiscing elit duis tristique. Ultrices gravida dictum fusce ut. At in tellus integer feugiat scelerisque varius morbi enim. Turpis nunc eget lorem dolor. Facilisis gravida neque convallis a cras. Morbi tincidunt augue interdum velit. Nisl nunc mi ipsum faucibus. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Pulvinar pellentesque habitant morbi tristique senectus et netus. In mollis nunc sed id semper risus in hendrerit gravida. Netus et malesuada fames ac turpis egestas. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Arcu cursus vitae congue mauris rhoncus aenean vel elit. Diam donec adipiscing tristique risus nec. Orci sagittis eu volutpat odio facilisis. Morbi tristique senectus et netus et malesuada. Varius duis at consectetur lorem donec massa sapien faucibus. Neque laoreet suspendisse interdum consectetur libero id faucibus. Mollis nunc sed id semper risus in. Laoreet non curabitur gravida arcu ac. Velit laoreet id donec ultrices tincidunt arcu. Montes nascetur ridiculus mus mauris vitae. Luctus venenatis lectus magna fringilla urna porttitor. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis.', id: 1 },
      { title: 'top 5 CSS tips', body: 'Facilisi nullam vehicula ipsum a arcu cursus vitae. Felis bibendum ut tristique et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Diam ut venenatis tellus in metus. Pharetra vel turpis nunc eget lorem dolor sed. Urna duis convallis convallis tellus id interdum velit laoreet id. Faucibus scelerisque eleifend donec pretium vulputate. Sit amet purus gravida quis. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Massa id neque aliquam vestibulum morbi blandit cursus. Viverra orci sagittis eu volutpat. In tellus integer feugiat scelerisque varius morbi enim nunc. Ut consequat semper viverra nam libero justo laoreet sit amet. Ac tortor vitae purus faucibus ornare suspendisse sed nisi. Cras fermentum odio eu feugiat pretium. Varius quam quisque id diam vel quam elementum pulvinar etiam. Pulvinar elementum integer enim neque. Blandit cursus risus at ultrices mi tempus. Velit scelerisque in dictum non consectetur a erat nam at. Facilisis gravida neque convallis a cras. Dictumst quisque sagittis purus sit amet volutpat consequat. Posuere ac ut consequat semper viverra nam libero justo. Nibh praesent tristique magna sit amet purus. Tincidunt dui ut ornare lectus sit amet est. Odio morbi quis commodo odio aenean sed adipiscing diam donec. Cursus turpis massa tincidunt dui ut ornare lectus sit. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Id ornare arcu odio ut sem nulla. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. In ornare quam viverra orci sagittis eu volutpat. Quis auctor elit sed vulputate mi sit amet. Facilisis gravida neque convallis a cras semper auctor. Laoreet suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Imperdiet massa tincidunt nunc pulvinar. Tortor at risus viverra adipiscing at in tellus. Aliquam ut porttitor leo a diam sollicitudin. Pellentesque eu tincidunt tortor aliquam nulla. Accumsan sit amet nulla facilisi. Sed id semper risus in. Etiam erat velit scelerisque in. Mauris vitae ultricies leo integer malesuada nunc vel risus. Dignissim cras tincidunt lobortis feugiat vivamus at. In mollis nunc sed id semper risus in. Cras tincidunt lobortis feugiat vivamus at augue eget. Facilisis magna etiam tempor orci eu lobortis elementum. Accumsan in nisl nisi scelerisque eu ultrices.', id: 2 }
    ])
    const showPosts = ref(true)
 
    return { posts, showPosts }
  }
}
</script>
